<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fsas [
<!ELEMENT fsas (fsa)*>
<!ELEMENT fsa (id , date , author?, package, vulnerable , unaffected , bts , cve , desc)>
<!-- must be an integer -->
<!ELEMENT id (#PCDATA)>
<!-- in YYYY-MM-DD format -->
<!ELEMENT date (#PCDATA)>
<!-- your nick, then the From header will be something like "nick <noreply@frugalware.org>" -->
<!ELEMENT author (#PCDATA)>
<!-- package name, without group, version, etc -->
<!ELEMENT package (#PCDATA)>
<!-- the old version -->
<!ELEMENT vulnerable (#PCDATA)>
<!-- the new (backported) version -->
<!ELEMENT unaffected (#PCDATA)>
<!-- bts url -->
<!ELEMENT bts (#PCDATA)>
<!-- cve url -->
<!ELEMENT cve (#PCDATA)>
<!-- description, can be more than one line -->
<!ELEMENT desc (#PCDATA)>
]>

<!-- If you modify this file, be sure it's still valid - read /hooks/README! -->
<!-- FSA skeleton:
	<fsa>
		<id></id>
		<date></date>
		<author></author>
		<package></package>
		<vulnerable></vulnerable>
		<unaffected></unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-</cve>
		<desc></desc>
	</fsa>
-->

<fsas>
	<fsa>
               <id>832</id>
               <date>2014-05-17</date>
               <author>kikadf</author>
               <package>actionpack</package>
               <vulnerable>3.2.6-2arcturus1</vulnerable>
               <unaffected>3.2.6-2arcturus2</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0081
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0082
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0130</cve>
               <desc>The actionview/lib/action_view/helpers/number_helper.rb contains multiple cross-site scripting vulnerabilities. The actionpack/lib/action_view/template/text.rb performs symbol interning on MIME type strings, allowing remote denial-of-service attacks via increased memory consumption.
			A directory traversal vulnerability in actionpack/lib/abstract_controller/base.rb allows remote attackers to read arbitrary files.</desc>
       </fsa>
	<fsa>
		<id>831</id>
		<date>2014-05-16</date>
		<author>kikadf</author>
		<package>libxml2</package>
		<vulnerable>2.8.0-1</vulnerable>
		<unaffected>2.8.0-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-5134
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-0339
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-2877
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0191</cve>
		<desc>It was discovered that libxml2 had a heap-based buffer underflow when parsing entities. It was discovered that libxml2 would load XML external entities by default.
			It was discovered that libxml2 incorrectly handled documents that end abruptly. Daniel Berrange discovered that libxml2 would incorrectly perform entity substitution even when requested not to.</desc>
	</fsa>
	<fsa>
		<id>830</id>
		<date>2014-05-16</date>
		<author>kikadf</author>
		<package>dovecot</package>
		<vulnerable>2.1.8-2</vulnerable>
		<unaffected>2.1.8-3arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3430</cve>
		<desc>It was discovered that Dovecot incorrectly handled closing inactive SSL/TLS connections.</desc>
	</fsa>
	<fsa>
		<id>829</id>
		<date>2014-05-15</date>
		<author>kikadf</author>
		<package>django</package>
		<vulnerable>1.5.2-2arcturus1</vulnerable>
		<unaffected>1.5.2-2arcturus2</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1418</cve>
		<desc>Stephen Stewart, Michael Nelson, Natalia Bidart and James Westby discovered that Django improperly removed Vary and Cache-Control headers from HTTP responses when replying to a request from an Internet Explorer or Chrome Frame client.
			Peter Kuma and Gavin Wahl discovered that Django did not correctly validate some malformed URLs, which are accepted by some browsers.</desc>
	</fsa>
	<fsa>
		<id>828</id>
		<date>2014-05-15</date>
		<author>James Buren</author>
		<package>kernel</package>
		<vulnerable>3.10-6</vulnerable>
		<unaffected>3.10-7</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0196
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1737
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1738
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2851
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3122</cve>
		<desc>Jiri Slaby discovered a race condition in the pty layer, which could lead to denial of service or privilege escalation.
			Matthew Daley discovered that missing input sanitising in the FDRAWCMD ioctl and an information leak could result in privilege escalation.
			Incorrect reference counting in the ping_init_sock() function allows denial of service or privilege escalation. Incorrect locking of memory can result in local denial of service.</desc>
	</fsa>
	<fsa>
		<id>827</id>
		<date>2014-05-14</date>
		<author>kikadf</author>
		<package>libxfont</package>
		<vulnerable>1.4.5-2arcturus2</vulnerable>
		<unaffected>1.4.5-2arcturus3</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0209
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0210
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0211</cve>
		<desc>Integer overflow of allocations in font metadata file parsing could allow a local user who is already authenticated to the X server to overwrite other memory in the heap.
			Libxfont does not validate length fields when parsing xfs protocol replies allowing to write past the bounds of allocated memory when storing the returned data from the font server.
			Integer overflows calculating memory needs for xfs replies could result in allocating too little memory and then writing the returned data from the font server past the end of the allocated buffer.</desc>
	</fsa>
	<fsa>
		<id>826</id>
		<date>2014-05-09</date>
		<author>kikadf</author>
		<package>rxvt-unicode</package>
		<vulnerable>9.18-1</vulnerable>
		<unaffected>9.18-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-3121</cve>
		<desc>Phillip Hallam-Baker discovered that window property values could be queried in rxvt-unicode, resulting in the potential execution of arbitrary commands.</desc>
	</fsa>
	<fsa>
		<id>825</id>
		<date>2014-05-07</date>
		<author>kikadf</author>
		<package>libtiff</package>
		<vulnerable>3.9.5-1</vulnerable>
		<unaffected>3.9.5-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-1173
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-2088
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-2113
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3401
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-4447
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-4564
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-5581
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1960
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1961
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4231
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4232
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4243
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4244</cve>
		<desc>It was discovered that LibTIFF incorrectly handled certain malformed images when using the gif2tiff tool.
			If a user or automated system were tricked into opening a specially crafted GIF image, a remote attacker could crash the application, leading to a denial of service, or possibly execute arbitrary code with user privileges.</desc>
	</fsa>
	<fsa>
               <id>824</id>
               <date>2014-05-07</date>
               <author>kikadf</author>
               <package>strongswan</package>
               <vulnerable>5.0.1-2arcturus1</vulnerable>
               <unaffected>5.0.1-2arcturus2</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2891</cve>
               <desc>A vulnerability has been found in the ASN.1 parser of strongSwan, an IKE/IPsec suite used to establish IPsec protected links.</desc>
       </fsa>
	<fsa>
		<id>823</id>
		<date>2014-05-07</date>
		<author>kikadf</author>
		<package>openssl</package>
		<vulnerable>1.0.1-5arcturus3</vulnerable>
		<unaffected>1.0.1-5arcturus4</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0198</cve>
		<desc>It was discovered that OpenSSL incorrectly handled memory in the do_ssl3_write() function. 
			A remote attacker could use this issue to possibly cause OpenSSL to crash, resulting in a denial of service.</desc>
	</fsa>
	<fsa>
               <id>822</id>
               <date>2014-04-30</date>
               <author>kikadf</author>
               <package>libmms</package>
               <vulnerable>0.6.2-1</vulnerable>
               <unaffected>0.6.2-2arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2892</cve>
               <desc>Alex Chapman discovered that a buffer overflow in processing "MMS over HTTP" messages could result in the execution of arbitrary code.</desc>
       </fsa>
	<fsa>
		<id>821</id>
		<date>2014-04-28</date>
		<author>kikadf</author>
		<package>qemu</package>
		<vulnerable>1.5.2-3arcturus3</vulnerable>
		<unaffected>1.5.2-3arcturus4</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4544
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2894</cve>
		<desc>Michael S. Tsirkin discovered that QEMU incorrectly handled vmxnet3 devices.
			Benoît Canet discovered that QEMU incorrectly handled SMART self-tests. 
			A local guest could possibly use this issue to cause a denial of service, or possibly execute arbitrary code on the host.</desc>
	</fsa>
	<fsa>
		<id>820</id>
		<date>2014-04-26</date>
		<author>kikadf</author>
		<package>drupal7</package>
		<vulnerable>7.22-2arcturus1</vulnerable>
		<unaffected>7.22-2arcturus2</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2983</cve>
		<desc>An information disclosure vulnerability was discovered in Drupal, a fully-featured content management framework. When pages are cached for anonymous users, form state may leak between anonymous users. Sensitive or private information recorded for one anonymous user could thus be disclosed to other users interacting with the same form at the same time.</desc>
	</fsa>
	<fsa>
		<id>819</id>
		<date>2014-04-26</date>
		<author>kikadf</author>
		<package>drupal6</package>
		<vulnerable>6.30-1arcturus1</vulnerable>
		<unaffected>6.31-1arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2983</cve>
		<desc>An information disclosure vulnerability was discovered in Drupal, a fully-featured content management framework. When pages are cached for anonymous users, form state may leak between anonymous users. Sensitive or private information recorded for one anonymous user could thus be disclosed to other users interacting with the same form at the same time.</desc>
	</fsa>
	<fsa>
		<id>818</id>
		<date>2014-04-25</date>
		<author>kikadf</author>
		<package>cups</package>
		<vulnerable>1.6.1-3arcturus1</vulnerable>
		<unaffected>1.6.1-3arcturus2</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2856</cve>
		<desc>Alex Korobkin discovered that the CUPS web interface incorrectly protected against cross-site scripting (XSS) attacks.</desc>
	</fsa>
	<fsa>
		<id>817</id>
		<date>2014-04-22</date>
		<author>kikadf</author>
		<package>django</package>
		<vulnerable>1.5.2-1</vulnerable>
		<unaffected>1.5.2-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0472
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0473
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0474</cve>
		<desc>Benjamin Bach discovered that Django incorrectly handled dotted Python paths when using the reverse() function.
			Paul McMillan discovered that Django incorrectly cached certain pages that contained CSRF cookies.
			Michael Koziarski discovered that Django did not always perform explicit conversion of certain fields when using a MySQL database.</desc>
	</fsa>
	<fsa>
		<id>816</id>
		<date>2014-04-20</date>
		<author>kikadf</author>
		<package>qemu</package>
		<vulnerable>1.5.2-3arcturus2</vulnerable>
		<unaffected>1.5.2-3arcturus3</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0150</cve>
		<desc>Michael S. Tsirkin of Red Hat discovered a buffer overflow flaw in the way qemu processed MAC addresses table update requests from the guest.
			A privileged guest user could use this flaw to corrupt qemu process memory on the host, which could potentially result in arbitrary code execution on the host with the privileges of the qemu process.</desc>
	</fsa>
	<fsa>
		<id>815</id>
		<date>2014-04-18</date>
		<author>kikadf</author>
		<package>openssl</package>
		<vulnerable>1.0.1-5arcturus2</vulnerable>
		<unaffected>1.0.1-5arcturus3</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-5298</cve>
		<desc>A read buffer can be freed even when it still contains data that is used later on, leading to a use-after-free.
			Given a race condition in a multi-threaded application it may permit an attacker to inject data from one connection into another or cause denial of service.</desc>
	</fsa>
	<fsa>
               <id>814</id>
               <date>2014-04-18</date>
               <author>kikadf</author>
               <package>ntp</package>
               <vulnerable>4.2.6p5-2</vulnerable>
               <unaffected>4.2.6p5-3arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-5211</cve>
               <desc>The monlist feature in ntp_request.c in ntpd in NTP before 4.2.7p26 allows remote attackers to cause a denial of service (traffic amplification) via forged (1) REQ_MON_GETLIST or (2) REQ_MON_GETLIST_1 requests, as exploited in the wild in December 2013.</desc>
       </fsa>
	<fsa>
               <id>813</id>
               <date>2014-04-18</date>
               <author>kikadf</author>
               <package>openssh</package>
               <vulnerable>6.1p1-1</vulnerable>
               <unaffected>6.1p1-2arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4548
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2532
						http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2653</cve>
               <desc>Jann Horn discovered that OpenSSH incorrectly handled wildcards in AcceptEnv lines. A remote attacker could use this issue to trick OpenSSH into accepting any environment variable that contains the characters before the wildcard character.
			Matthew Vernon reported that if a SSH server offers a HostCertificate that the ssh client doesn't accept, then the client doesn't check the DNS for SSHFP records. As a consequence a malicious server can disable SSHFP-checking by presenting a certificate.</desc>
       </fsa>
	<fsa>
		<id>812</id>
		<date>2014-04-18</date>
		<author>kikadf</author>
		<package>python</package>
		<vulnerable>2.7.5-1</vulnerable>
		<unaffected>2.7.5-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4238
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1912</cve>
		<desc>Ryan Sleevi discovered that NULL characters in the subject alternate names of SSL cerficates were parsed incorrectly.
			Ryan Smith-Roberts discovered a buffer overflow in the socket.recvfrom_into() function.</desc>
	</fsa>
	<fsa>
               <id>811</id>
               <date>2014-04-17</date>
               <author>kikadf</author>
               <package>imaging</package>
               <vulnerable>1.1.7-4</vulnerable>
               <unaffected>1.1.7-5arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1932
		       http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1933</cve>
               <desc>Jakub Wilk discovered that the Python Imaging Library incorrectly handled temporary files.
		       A local attacker could possibly use this issue to overwrite arbitrary files, or gain access to temporary file contents.</desc>
       </fsa>
	<fsa>
               <id>810</id>
               <date>2014-04-17</date>
               <author>kikadf</author>
               <package>xalan-j</package>
               <vulnerable>2.7.1-2</vulnerable>
               <unaffected>2.7.1-3arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0107</cve>
               <desc>Nicolas Gregoire discovered several vulnerabilities in libxalan2-java, a Java library for XSLT processing. Crafted XSLT programs could access system properties or load arbitrary classes, resulting in information disclosure and, potentially, arbitrary code execution.</desc>
       </fsa>
	<fsa>
               <id>809</id>
               <date>2014-04-17</date>
               <author>kikadf</author>
               <package>wordpress</package>
               <vulnerable>3.5.1-1</vulnerable>
               <unaffected>3.9-1arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0165
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0166</cve>
               <desc>A user with a contributor role, using a specially crafted request, can publish posts, which is reserved for users of the next-higher role.
		       Jon Cave of the WordPress security team discovered that the wp_validate_auth_cookie function in wp-includes/pluggable.php does not properly determine the validity of authentication cookies, allowing a remote attacker to obtain access via a forged cookie.</desc>
       </fsa>
	<fsa>
               <id>808</id>
               <date>2014-04-17</date>
               <author>kikadf</author>
               <package>strongswan</package>
               <vulnerable>5.0.1-1</vulnerable>
               <unaffected>5.0.1-2arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-5018
		        http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6075
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2338</cve>
               <desc>A vulnerability has been found in the ASN.1 parser of strongSwan, an IKE daemon used to establish IPsec protected links.
			An authentication bypass vulnerability was found in charon, the daemon handling IKEv2 in strongSwan, an IKE/IPsec suite. The state machine handling the security association (IKE_SA) handled some state transitions incorrectly.</desc>
       </fsa>
	<fsa>
               <id>807</id>
               <date>2014-04-17</date>
               <author>kikadf</author>
               <package>samba</package>
               <vulnerable>3.6.9-4arcturus1</vulnerable>
               <unaffected>3.6.23-1arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4496
		       http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6442</cve>
               <desc>Andrew Bartlett discovered that Samba did not properly enforce the password guessing protection mechanism for all interfaces.
		       Samba have a flaw in the smbcacls command. If smbcacls is used with the "-C|--chown name" or "-G|--chgrp name"
		       command options it will remove the existing ACL on the object being modified, leaving the file or directory unprotected.</desc>
       </fsa>
	<fsa>
               <id>806</id>
               <date>2014-04-17</date>
               <author>kikadf</author>
               <package>postfixadmin</package>
               <vulnerable>2.3.6-1</vulnerable>
               <unaffected>2.3.6-2arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2655</cve>
               <desc>An SQL injection vulnerability was discovered in postfixadmin, a web administration interface for the Postfix Mail Transport Agent, which allowed authenticated users to make arbitrary manipulations to the database.</desc>
       </fsa>
	<fsa>
               <id>805</id>
               <date>2014-04-16</date>
               <author>kikadf</author>
               <package>net-snmp</package>
               <vulnerable>5.7.1-3</vulnerable>
               <unaffected>5.7.1-4arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-6151
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2284
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2285</cve>
               <desc>Ken Farnen discovered that Net-SNMP incorrectly handled AgentX timeouts. It was discovered that the Net-SNMP ICMP-MIB incorrectly validated input.
			Viliam Púčik discovered that the Net-SNMP perl trap handler incorrectly handled NULL arguments.</desc>
       </fsa>
	<fsa>
               <id>804</id>
               <date>2014-04-16</date>
               <author>kikadf</author>
               <package>jbigkit</package>
               <vulnerable>2.0-2</vulnerable>
               <unaffected>2.0-3arcturus1</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6369</cve>
               <desc>Florian Weimer of the Red Hat product security team discovered multiple buffer overflows in jbigkit, which could lead to the execution of arbitrary code when processing malformed images.</desc>
       </fsa>
	<fsa>
               <id>803</id>
               <date>2014-04-16</date>
               <author>kikadf</author>
               <package>curl</package>
               <vulnerable>7.26.0-2arcturus2</vulnerable>
               <unaffected>7.26.0-2arcturus3</unaffected>
               <bts></bts>
               <cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0138
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0139</cve>
               <desc>Steve Holme discovered that libcurl can in some circumstances re-use the wrong connection when asked to do transfers using other protocols than HTTP and FTP.
			Richard Moore from Westpoint Ltd. reported that libcurl does not behave compliant to RFC 2828 under certain conditions and incorrectly validates wildcard SSL certificates containing literal IP addresses.</desc>
       </fsa>
	<fsa>
		<id>802</id>
		<date>2014-04-14</date>
		<author>kikadf</author>
		<package>libyaml</package>
		<vulnerable>0.1.4-3arcturus1</vulnerable>
		<unaffected>0.1.4-3arcturus2</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2525</cve>
		<desc>Ivan Fratric of the Google Security Team discovered a heap-based buffer overflow vulnerability in LibYAML, a fast YAML 1.1 parser and emitter library.</desc>
	</fsa>
	<fsa>
		<id>801</id>
		<date>2014-04-14</date>
		<author>kikadf</author>
		<package>apache</package>
		<vulnerable>2.2.23-2</vulnerable>
		<unaffected>2.2.23-3arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3499
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-4558
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-4929
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1862
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1896
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6438
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0098</cve>
		<desc>Ning Zhang and Amin Tora discovered that the mod_dav module incorrectly handled whitespace characters in CDATA sections.
			Rainer M Canavan discovered that the mod_log_config module incorrectly handled certain cookies.</desc>
	</fsa>
	<fsa>
		<id>800</id>
		<date>2014-04-14</date>
		<author>kikadf</author>
		<package>actionmailer</package>
		<vulnerable>3.2.6-1</vulnerable>
		<unaffected>3.2.6-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4389</cve>
		<desc>Aaron Neyer discovered that missing input sanitising in the logging component of Ruby Actionmailer could result in denial of service through a malformed e-mail message.</desc>
	</fsa>
	<fsa>
		<id>799</id>
		<date>2014-04-14</date>
		<author>kikadf</author>
		<package>actionpack</package>
		<vulnerable>3.2.6-1</vulnerable>
		<unaffected>3.2.6-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3424
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3463
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3465
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-0155
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1855
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1857
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4389
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4491
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6414
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6415
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6417</cve>
		<desc>Toby Hsieh, Peter McLarnan, Ankit Gupta, Sudhir Rao and Kevin Reintjes discovered multiple cross-site scripting and denial of service vulnerabilities in Ruby Actionpack.</desc>
	</fsa>
	<fsa>
		<id>798</id>
		<date>2014-04-12</date>
		<author>kikadf</author>
		<package>a2ps</package>
		<vulnerable>4.14-4</vulnerable>
		<unaffected>4.14-5arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2001-1953
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0466</cve>
		<desc>The spy_user function which is called when a2ps is invoked with the --debug flag insecurely used temporary files.
			Brian M. Carlson reported that a2ps's fixps script does not invoke gs with the -dSAFER option. 
			Consequently executing fixps on a malicious PostScript file could result in files being deleted or arbitrary commands being executed with the privileges of the user running fixps.</desc>
	</fsa>
	<fsa>
		<id>797</id>
		<date>2014-04-08</date>
		<author>James Buren</author>
		<package>openssl</package>
		<vulnerable>1.0.1-5arcturus1</vulnerable>
		<unaffected>1.0.1-5arcturus2</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0160</cve>
		<desc>A vulnerability has been discovered in OpenSSL's support for the TLS/DTLS Heartbeat extension. 
			Up to 64KB of memory from either client or server can be recovered by an attacker. This vulnerability might allow an attacker to compromise the private key and other sensitive data in memory.</desc>
	</fsa>
	<fsa>
		<id>796</id>
		<date>2014-03-15</date>
		<author>kikadf</author>
		<package>lighttpd</package>
		<vulnerable>1.4.32-2</vulnerable>
		<unaffected>1.4.35-1arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2323
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-2324
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4508
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4559
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4560</cve>
		<desc>Jann Horn discovered that specially crafted host names can be used to inject arbitrary MySQL queries in lighttpd servers using the MySQL virtual hosting module (mod_mysql_vhost).
			Jann Horn discovered that specially crafted host names can be used to traverse outside of the document root under certain situations in lighttpd servers using either the mod_mysql_vhost, mod_evhost, or mod_simple_vhost virtual hosting modules.</desc>
	</fsa>
	<fsa>
		<id>795</id>
		<date>2014-03-14</date>
		<author>kikadf</author>
		<package>mutt-devel</package>
		<vulnerable>1.5.21-3</vulnerable>
		<unaffected>1.5.21-4arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0467</cve>
		<desc>Beatrice Torracca and Evgeni Golov discovered a buffer overflow in the mutt mailreader. Malformed RFC2047 header lines could result in denial of service or potentially the execution of arbitrary code.</desc>
	</fsa>
	<fsa>
		<id>794</id>
		<date>2014-03-13</date>
		<author>kikadf</author>
		<package>php</package>
		<vulnerable>5.3.26-1</vulnerable>
		<unaffected>5.3.26-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4413
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4248
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6420
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6712
			http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1943</cve>
		<desc>It was discovered that file, a file type classification tool, contains a flaw in the handling of indirect magic rules in the libmagic library, which leads to an infinite recursion when trying to determine the file type of certain files.</desc>
	</fsa>
	<fsa>
		<id>793</id>
		<date>2014-03-13</date>
		<author>kikadf</author>
		<package>icedtea-web</package>
		<vulnerable>1.3.1-1</vulnerable>
		<unaffected>1.3.1-2arcturus1</unaffected>
		<bts></bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-6493</cve>
		<desc>Michael Scherer discovered that IcedTea Web created temporary directories in an unsafe fashion.</desc>
	</fsa>
	<fsa>
		<id>792</id>
		<date>2014-03-13</date>
		<author>kikadf</author>
		<package>cups-filters</package>
		<vulnerable>1.0.24-1</vulnerable>
		<unaffected>1.0.24-2arcturus1</unaffected>